version: '3.9'

services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_DEBUG: 1
    command: >
      sh -c "python3 -m flask run --host=0.0.0.0 --debugger"


